package laprecordtracker.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import laprecordtracker.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.05.09 16:22:57 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KierrosaikaTest {



  // Generated by ComTest BEGIN
  /** testParse147 */
  @Test
  public void testParse147() {    // Kierrosaika: 147
    Kierrosaika kierrosaika = new Kierrosaika(); 
    kierrosaika.parse("    4 |  Nissan GT-R     | 02.25.733 "); 
    assertEquals("From: Kierrosaika line: 150", 4, kierrosaika.getTunnusNro()); 
    assertEquals("From: Kierrosaika line: 151", true, kierrosaika.toString().startsWith("4|Nissan GT-R|02.25.733|")); 
    kierrosaika.rekisteroi(); 
    int n = kierrosaika.getTunnusNro(); 
    kierrosaika.parse(""+(n+20)); 
    kierrosaika.rekisteroi(); 
    assertEquals("From: Kierrosaika line: 157", n+20+1, kierrosaika.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString177 */
  @Test
  public void testToString177() {    // Kierrosaika: 177
    Kierrosaika kierrosaika = new Kierrosaika(); 
    kierrosaika.parse("    2  |   Ford Escort    | 2.43.523"); 
    assertEquals("From: Kierrosaika line: 180", true, kierrosaika.toString().startsWith("2|Ford Escort|2.43.523")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi201 */
  @Test
  public void testRekisteroi201() {    // Kierrosaika: 201
    Kierrosaika zonda1 = new Kierrosaika(); 
    assertEquals("From: Kierrosaika line: 203", 0, zonda1.getTunnusNro()); 
    zonda1.rekisteroi(); 
    Kierrosaika zonda2 = new Kierrosaika(); 
    zonda2.rekisteroi(); 
    int n1 = zonda1.getTunnusNro(); 
    int n2 = zonda2.getTunnusNro(); 
    assertEquals("From: Kierrosaika line: 209", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone223 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone223() throws CloneNotSupportedException {    // Kierrosaika: 223
    Kierrosaika kAika = new Kierrosaika(); 
    kAika.parse("     2   |     23.13.124 |  Zonda R"); 
    Kierrosaika kopio = kAika.clone(); 
    assertEquals("From: Kierrosaika line: 228", kAika.toString(), kopio.toString()); 
    kAika.parse("    5   |  54.34.752   |   CLS"); 
    assertEquals("From: Kierrosaika line: 230", false, kopio.toString().equals(kAika.toString())); 
  } // Generated by ComTest END
}