package laprecordtracker.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import laprecordtracker.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.23 20:15:15 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KierrosaikaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi62 */
  @Test
  public void testRekisteroi62() {    // Kierrosaika: 62
    Kierrosaika zonda1 = new Kierrosaika(); 
    assertEquals("From: Kierrosaika line: 64", 0, zonda1.getTunnusNro()); 
    zonda1.rekisteroi(); 
    Kierrosaika zonda2 = new Kierrosaika(); 
    zonda2.rekisteroi(); 
    int n1 = zonda1.getTunnusNro(); 
    int n2 = zonda2.getTunnusNro(); 
    assertEquals("From: Kierrosaika line: 70", n2-1, n1); 
  } // Generated by ComTest END
}