package laprecordtracker.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import laprecordtracker.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.24 21:21:27 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KierrosajatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa30 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa30() throws SailoException {    // Kierrosajat: 30
    Kierrosajat kierrosajat = new Kierrosajat(); 
    Kierrosaika zonda1 = new Kierrosaika(), zonda2 = new Kierrosaika(); 
    assertEquals("From: Kierrosajat line: 34", 0, kierrosajat.getLkm()); 
    kierrosajat.lisaa(zonda1); assertEquals("From: Kierrosajat line: 35", 1, kierrosajat.getLkm()); 
    kierrosajat.lisaa(zonda2); assertEquals("From: Kierrosajat line: 36", 2, kierrosajat.getLkm()); 
    kierrosajat.lisaa(zonda1); assertEquals("From: Kierrosajat line: 37", 3, kierrosajat.getLkm()); 
    assertEquals("From: Kierrosajat line: 38", zonda1, kierrosajat.anna(0)); 
    assertEquals("From: Kierrosajat line: 39", zonda2, kierrosajat.anna(1)); 
    assertEquals("From: Kierrosajat line: 40", zonda1, kierrosajat.anna(2)); 
    assertEquals("From: Kierrosajat line: 41", false, kierrosajat.anna(1) == zonda1); 
    assertEquals("From: Kierrosajat line: 42", true, kierrosajat.anna(1) == zonda2); 
    kierrosajat.lisaa(zonda1); assertEquals("From: Kierrosajat line: 43", 4, kierrosajat.getLkm()); 
    kierrosajat.lisaa(zonda1); assertEquals("From: Kierrosajat line: 44", 5, kierrosajat.getLkm()); 
  } // Generated by ComTest END
}