package laprecordtracker.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import laprecordtracker.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.23 23:08:33 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KierrosajatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa29 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa29() throws SailoException {    // Kierrosajat: 29
    Kierrosajat kierrosajat = new Kierrosajat(); 
    Kierrosaika zonda1 = new Kierrosaika(), zonda2 = new Kierrosaika(); 
    assertEquals("From: Kierrosajat line: 33", 0, kierrosajat.getLkm()); 
    kierrosajat.lisaa(zonda1); assertEquals("From: Kierrosajat line: 34", 1, kierrosajat.getLkm()); 
    kierrosajat.lisaa(zonda2); assertEquals("From: Kierrosajat line: 35", 2, kierrosajat.getLkm()); 
    kierrosajat.lisaa(zonda1); assertEquals("From: Kierrosajat line: 36", 3, kierrosajat.getLkm()); 
    assertEquals("From: Kierrosajat line: 37", zonda1, kierrosajat.anna(0)); 
    assertEquals("From: Kierrosajat line: 38", zonda2, kierrosajat.anna(1)); 
    assertEquals("From: Kierrosajat line: 39", zonda1, kierrosajat.anna(2)); 
    assertEquals("From: Kierrosajat line: 40", false, kierrosajat.anna(1) == zonda1); 
    assertEquals("From: Kierrosajat line: 41", true, kierrosajat.anna(1) == zonda2); 
    try {
    assertEquals("From: Kierrosajat line: 42", zonda1, kierrosajat.anna(3)); 
    fail("Kierrosajat: 42 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kierrosajat.lisaa(zonda1); assertEquals("From: Kierrosajat line: 43", 4, kierrosajat.getLkm()); 
    kierrosajat.lisaa(zonda1); assertEquals("From: Kierrosajat line: 44", 5, kierrosajat.getLkm()); 
    try {
    kierrosajat.lisaa(zonda1); 
    fail("Kierrosajat: 45 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}