package laprecordtracker.test;
// Generated by ComTest BEGIN
import laprecordtracker.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.24 22:00:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KilparadatTest {



  // Generated by ComTest BEGIN
  /** testIterator73 */
  @Test
  public void testIterator73() {    // Kilparadat: 73
    Kilparadat kilparadat = new Kilparadat(); 
    Kilparata kilpa21 = new Kilparata(2); kilparadat.lisaa(kilpa21); 
    Kilparata kilpa11 = new Kilparata(1); kilparadat.lisaa(kilpa11); 
    Kilparata kilpa22 = new Kilparata(2); kilparadat.lisaa(kilpa22); 
    Kilparata kilpa12 = new Kilparata(1); kilparadat.lisaa(kilpa12); 
    Kilparata kilpa23 = new Kilparata(2); kilparadat.lisaa(kilpa23); 
    Iterator<Kilparata> i2=kilparadat.iterator(); 
    assertEquals("From: Kilparadat line: 85", kilpa21, i2.next()); 
    assertEquals("From: Kilparadat line: 86", kilpa11, i2.next()); 
    assertEquals("From: Kilparadat line: 87", kilpa22, i2.next()); 
    assertEquals("From: Kilparadat line: 88", kilpa12, i2.next()); 
    assertEquals("From: Kilparadat line: 89", kilpa23, i2.next()); 
    try {
    assertEquals("From: Kilparadat line: 90", kilpa12, i2.next()); 
    fail("Kilparadat: 90 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int jnrot[] = { 2,1,2,1,2} ; 
    for (Kilparata kil : kilparadat) {
    assertEquals("From: Kilparadat line: 96", jnrot[n], kil.getKierrosaikaNro()); n++; 
    }
    assertEquals("From: Kilparadat line: 99", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKilparadat114 */
  @Test
  public void testAnnaKilparadat114() {    // Kilparadat: 114
    Kilparadat kilparadat = new Kilparadat(); 
    Kilparata kilpa21 = new Kilparata(2); kilparadat.lisaa(kilpa21); 
    Kilparata kilpa11 = new Kilparata(1); kilparadat.lisaa(kilpa11); 
    Kilparata kilpa22 = new Kilparata(2); kilparadat.lisaa(kilpa22); 
    Kilparata kilpa12 = new Kilparata(1); kilparadat.lisaa(kilpa12); 
    Kilparata kilpa23 = new Kilparata(2); kilparadat.lisaa(kilpa23); 
    Kilparata kilpa51 = new Kilparata(5); kilparadat.lisaa(kilpa51); 
    List<Kilparata> loytyneet; 
    loytyneet = kilparadat.annaKilparadat(3); 
    assertEquals("From: Kilparadat line: 127", 0, loytyneet.size()); 
    loytyneet = kilparadat.annaKilparadat(1); 
    assertEquals("From: Kilparadat line: 129", 2, loytyneet.size()); 
    assertEquals("From: Kilparadat line: 130", true, loytyneet.get(0) == kilpa11); 
    assertEquals("From: Kilparadat line: 131", true, loytyneet.get(1) == kilpa12); 
    loytyneet = kilparadat.annaKilparadat(5); 
    assertEquals("From: Kilparadat line: 133", 1, loytyneet.size()); 
    assertEquals("From: Kilparadat line: 134", true, loytyneet.get(0) == kilpa51); 
  } // Generated by ComTest END
}