package laprecordtracker.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import laprecordtracker.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.14 14:54:17 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KilparataTest {



  // Generated by ComTest BEGIN
  /** testToString52 */
  @Test
  public void testToString52() {    // Kilparata: 52
    Kilparata kilparata = new Kilparata(); 
    kilparata.parse("    5 |    1   |    Nordschleife  "); 
    assertEquals("From: Kilparata line: 55", "5|1|Nordschleife", kilparata.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse69 */
  @Test
  public void testParse69() {    // Kilparata: 69
    Kilparata kilparata = new Kilparata(); 
    kilparata.parse("    5 |    1   |    Nordschleife  "); 
    assertEquals("From: Kilparata line: 72", 1, kilparata.getPeliNro()); 
    assertEquals("From: Kilparata line: 73", "5|1|Nordschleife", kilparata.toString()); 
    kilparata.rekisteroi(); 
    int n = kilparata.getTunnusNro(); 
    kilparata.parse(""+(n+20)); 
    kilparata.rekisteroi(); 
    assertEquals("From: Kilparata line: 79", n+20+1, kilparata.getTunnusNro()); 
    assertEquals("From: Kilparata line: 80", "" + (n+20+1) + "|1|Nordschleife", kilparata.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi95 */
  @Test
  public void testRekisteroi95() {    // Kilparata: 95
    Kilparata kilpa1 = new Kilparata(); 
    assertEquals("From: Kilparata line: 97", 0, kilpa1.getTunnusNro()); 
    kilpa1.rekisteroi(); 
    Kilparata kilpa2 = new Kilparata(); 
    kilpa2.rekisteroi(); 
    int n1 = kilpa1.getTunnusNro(); 
    int n2 = kilpa2.getTunnusNro(); 
    assertEquals("From: Kilparata line: 103", n2-1, n1); 
  } // Generated by ComTest END
}