package laprecordtracker.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import laprecordtracker.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.24 21:18:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KilparataTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi46 */
  @Test
  public void testRekisteroi46() {    // Kilparata: 46
    Kilparata kilpa1 = new Kilparata(); 
    assertEquals("From: Kilparata line: 48", 0, kilpa1.getTunnusNro()); 
    kilpa1.rekisteroi(); 
    Kilparata kilpa2 = new Kilparata(); 
    kilpa2.rekisteroi(); 
    int n1 = kilpa1.getTunnusNro(); 
    int n2 = kilpa2.getTunnusNro(); 
    assertEquals("From: Kilparata line: 54", n2-1, n1); 
  } // Generated by ComTest END
}