package laprecordtracker.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import laprecordtracker.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.05.07 20:20:19 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class LapRecordTrackerTest {



  // Generated by ComTest BEGIN
  /** testAnnaKilparadat87 */
  @Test
  public void testAnnaKilparadat87() {    // LapRecordTracker: 87
    LapRecordTracker laprecordtracker = new LapRecordTracker(); 
    Kierrosaika zonda1 = new Kierrosaika(), zonda2 = new Kierrosaika(), zonda3 = new Kierrosaika(); 
    zonda1.rekisteroi(); zonda2.rekisteroi(); zonda3.rekisteroi(); 
    int id1 = zonda1.getTunnusNro(); 
    int id2 = zonda2.getTunnusNro(); 
    Kilparata kilpa11 = new Kilparata(id1); laprecordtracker.lisaa(kilpa11); 
    Kilparata kilpa12 = new Kilparata(id1); laprecordtracker.lisaa(kilpa12); 
    Kilparata kilpa21 = new Kilparata(id2); laprecordtracker.lisaa(kilpa21); 
    Kilparata kilpa22 = new Kilparata(id2); laprecordtracker.lisaa(kilpa22); 
    Kilparata kilpa23 = new Kilparata(id2); laprecordtracker.lisaa(kilpa23); 
    List<Kilparata> loytyneet; 
    loytyneet = laprecordtracker.annaKilparadat(zonda3); 
    assertEquals("From: LapRecordTracker line: 103", 0, loytyneet.size()); 
    loytyneet = laprecordtracker.annaKilparadat(zonda1); 
    assertEquals("From: LapRecordTracker line: 105", 2, loytyneet.size()); 
    assertEquals("From: LapRecordTracker line: 106", true, loytyneet.get(0) == kilpa11); 
    assertEquals("From: LapRecordTracker line: 107", true, loytyneet.get(1) == kilpa12); 
    loytyneet = laprecordtracker.annaKilparadat(zonda2); 
    assertEquals("From: LapRecordTracker line: 109", 3, loytyneet.size()); 
    assertEquals("From: LapRecordTracker line: 110", true, loytyneet.get(0) == kilpa21); 
  } // Generated by ComTest END
}