package laprecordtracker.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import laprecordtracker.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.13 19:34:46 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PeliTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi66 */
  @Test
  public void testRekisteroi66() {    // Peli: 66
    Peli acorsa = new Peli(); 
    assertEquals("From: Peli line: 68", 0, acorsa.getTunnusNro()); 
    acorsa.rekisteroi(); 
    Peli automobilista = new Peli(); 
    automobilista.rekisteroi(); 
    int n1 = acorsa.getTunnusNro(); 
    int n2 = automobilista.getTunnusNro(); 
    assertEquals("From: Peli line: 74", n2-1, n1); 
  } // Generated by ComTest END
}