package laprecordtracker.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import laprecordtracker.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.14 15:25:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PeliTest {



  // Generated by ComTest BEGIN
  /** testToString98 */
  @Test
  public void testToString98() {    // Peli: 98
    Peli peli = new Peli(); 
    peli.parse("    5 |    1   |    Assetto Corsa  "); 
    assertEquals("From: Peli line: 101", "5|1|Assetto Corsa", peli.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse115 */
  @Test
  public void testParse115() {    // Peli: 115
    Peli peli = new Peli(); 
    peli.parse("    5 |    1   |    Assetto Corsa  "); 
    assertEquals("From: Peli line: 118", 1, peli.getPeliNro()); 
    assertEquals("From: Peli line: 119", "5|1|Assetto Corsa", peli.toString()); 
    peli.rekisteroi(); 
    int n = peli.getTunnusNro(); 
    peli.parse(""+(n+20)); 
    peli.rekisteroi(); 
    assertEquals("From: Peli line: 125", n+20+1, peli.getTunnusNro()); 
    assertEquals("From: Peli line: 126", "" + (n+20+1) + "|1|Assetto Corsa", peli.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi141 */
  @Test
  public void testRekisteroi141() {    // Peli: 141
    Peli acorsa = new Peli(); 
    assertEquals("From: Peli line: 143", 0, acorsa.getTunnusNro()); 
    acorsa.rekisteroi(); 
    Peli automobilista = new Peli(); 
    automobilista.rekisteroi(); 
    int n1 = acorsa.getTunnusNro(); 
    int n2 = automobilista.getTunnusNro(); 
    assertEquals("From: Peli line: 149", n2-1, n1); 
  } // Generated by ComTest END
}